<a href="https://colab.research.google.com/github/Apurva1205/-AI-Story/blob/main/Text_Classification_using_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Mount Google Drive to Colab
from google.colab import drive
drive.mount('/content/drive')




Mounted at /content/drive


In [2]:
import pandas as pd
data = pd.read_csv('/content/drive/My Drive/spam_ham_dataset.csv')

In [3]:
print(data.head(10)) # print first 10 rows


   Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   
5        2949   ham  Subject: ehronline web address change\r\nthis ...   
6        2793   ham  Subject: spring savings certificate - take 30 ...   
7        4185  spam  Subject: looking for medication ? we ` re the ...   
8        2641   ham  Subject: noms / actual flow for 2 / 26\r\nwe a...   
9        1870   ham  Subject: nominations for oct . 21 - 23 , 2000\...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0  
5          0  
6          0  
7          1  
8          0  
9          0  


In [4]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Read the CSV file
data = pd.read_csv('/content/drive/My Drive/spam_ham_dataset.csv')

# Prepare the data
data['label'] = np.where(data['label']=='spam', 1, 0) # Corrected label column name
X = data['text'] # Corrected text column name
y = data['label']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Vectorize the text data
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

# Train a Naive Bayes classifier
clf = MultinomialNB()
clf.fit(X_train, y_train)

# Evaluate the model on the test set
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.98      0.98      0.98       742
           1       0.96      0.95      0.95       293

    accuracy                           0.97      1035
   macro avg       0.97      0.96      0.97      1035
weighted avg       0.97      0.97      0.97      1035

[[729  13]
 [ 16 277]]


In [5]:
from sklearn.metrics import accuracy_score
# Print evaluation metrics
print("Evaluation Metrics:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Import the necessary libraries
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Interpret the evaluation metrics
print("\nInterpretation:")
print("Overall Accuracy:", round(accuracy_score(y_test, y_pred), 2))
print("Precision for ham (class 0):", round(precision_score(y_test, y_pred, pos_label=0), 2))
print("Precision for spam (class 1):", round(precision_score(y_test, y_pred, pos_label=1), 2))
print("Recall for ham (class 0):", round(recall_score(y_test, y_pred, pos_label=0), 2))
print("Recall for spam (class 1):", round(recall_score(y_test, y_pred, pos_label=1), 2))
print("F1-score for ham (class 0):", round(f1_score(y_test, y_pred, pos_label=0), 2))
print("F1-score for spam (class 1):", round(f1_score(y_test, y_pred, pos_label=1), 2))


Evaluation Metrics:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       742
           1       0.96      0.95      0.95       293

    accuracy                           0.97      1035
   macro avg       0.97      0.96      0.97      1035
weighted avg       0.97      0.97      0.97      1035

Confusion Matrix:
[[729  13]
 [ 16 277]]

Interpretation:
Overall Accuracy: 0.97
Precision for ham (class 0): 0.98
Precision for spam (class 1): 0.96
Recall for ham (class 0): 0.98
Recall for spam (class 1): 0.95
F1-score for ham (class 0): 0.98
F1-score for spam (class 1): 0.95


In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV

# Define the Naive Bayes classifier
nb = MultinomialNB()

# Define the hyperparameters to tune
hyperparameters = {'alpha': [0.01, 0.1, 1.0, 10.0]}

# Use GridSearchCV to search for the best hyperparameters
grid = GridSearchCV(nb, hyperparameters, cv=5)

# Fit the GridSearchCV object to the training data
grid.fit(X_train, y_train)

# Print the best hyperparameters
print("Best hyperparameters:", grid.best_params_)

# Get the predicted labels for the test set using the best model
y_pred = grid.predict(X_test)

# Evaluate the performance of the model using the test set
print("Evaluation Metrics:")
print(classification_report(y_test, y_pred))

# Print the confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Best hyperparameters: {'alpha': 0.01}
Evaluation Metrics:
              precision    recall  f1-score   support

           0       0.99      0.98      0.98       742
           1       0.95      0.97      0.96       293

    accuracy                           0.98      1035
   macro avg       0.97      0.97      0.97      1035
weighted avg       0.98      0.98      0.98      1035

Confusion Matrix:
[[727  15]
 [ 10 283]]


In [6]:
import nltk

nltk.download('punkt')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [7]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords

# Download stopwords and lemmatizer data
nltk.download('stopwords')
nltk.download('wordnet')

# Define text preprocessing function
def preprocess_text(text):
    # Tokenize text
    tokens = nltk.word_tokenize(text.lower())
    
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]
    
    # Stemming
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(token) for token in tokens]
    
    # Lemmatization
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    
    # Join tokens into a string
    preprocessed_text = " ".join(tokens)
    
    return preprocessed_text

# Example usage
text = "This is an example sentence for text preprocessing."
preprocessed_text = preprocess_text(text)
print(preprocessed_text)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


exampl sentenc text preprocess .


In [13]:
import pandas as pd

# Read the CSV file
data = pd.read_csv('/content/drive/My Drive/spam_ham_dataset.csv')

# check columns
print(data.columns)


Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')


In [14]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Read the CSV file
data = pd.read_csv('/content/drive/My Drive/spam_ham_dataset.csv')

# Define text preprocessing function
def preprocess_text(text):
    # Tokenize text
    tokens = nltk.word_tokenize(text.lower())

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]

    # Stemming
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(token) for token in tokens]

    # Lemmatization
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(token) for token in tokens]

    # Join tokens into a string
    preprocessed_text = " ".join(tokens)

    return preprocessed_text

# Apply preprocessing to the text column and create a new column with the preprocessed text
data['preprocessed_text'] = data['text'].apply(preprocess_text)

# Print the first few rows of the DataFrame to check the result
print(data.head())


   Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num                                  preprocessed_text  
0          0  subject : enron methanol ; meter # : 988291 fo...  
1          0  subject : hpl nom januari 9 , 2001 ( see attac...  
2          0  subject : neon retreat ho ho ho , ' around won...  
3          1  subject : photoshop , window , offic . cheap ....  
4          0  subject : : indian spring deal book teco pvr r...  


In [15]:
from sklearn.model_selection import train_test_split

# Split the preprocessed text and label into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data['preprocessed_text'], data['label_num'], test_size=0.2, random_state=42)

# Print the shapes of the training and testing sets to check the result
print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)


Training set shape: (4136,)
Testing set shape: (1035,)


In [16]:
from sklearn.feature_extraction.text import CountVectorizer

# Create a CountVectorizer object
vectorizer = CountVectorizer()

# Fit the vectorizer on the training data and transform both the training and testing data
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)


In [17]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, f1_score

# Train a Naive Bayes classifier on the training data
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

# Predict the labels of the testing data
y_pred = classifier.predict(X_test)

# Evaluate the performance of the classifier using accuracy and F1 score
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("F1 score:", f1)


Accuracy: 0.9719806763285024
F1 score: 0.9507640067911713


In [20]:
# Analyze the misclassified instances
for i in range(len(X_test.toarray())):
    if y_test.iloc[i] != y_pred[i]:
        print("Misclassified instance:")
        print("Text:", X_test[i])
        print("True label:", y_test.iloc[i])
        print("Predicted label:", y_pred[i])


Misclassified instance:
Text:   (0, 976)	1
  (0, 1645)	1
  (0, 2293)	1
  (0, 4279)	3
  (0, 4384)	1
  (0, 4547)	2
  (0, 4551)	1
  (0, 4648)	1
  (0, 4650)	1
  (0, 4824)	1
  (0, 5132)	4
  (0, 5181)	1
  (0, 5391)	1
  (0, 5520)	1
  (0, 5654)	1
  (0, 5726)	7
  (0, 5749)	1
  (0, 5839)	1
  (0, 5938)	2
  (0, 6087)	1
  (0, 6242)	2
  (0, 6353)	1
  (0, 6374)	1
  (0, 6408)	1
  (0, 6649)	5
  :	:
  (0, 34127)	1
  (0, 34315)	2
  (0, 34331)	1
  (0, 34377)	1
  (0, 34405)	1
  (0, 34459)	1
  (0, 34690)	1
  (0, 34721)	2
  (0, 34764)	1
  (0, 34807)	1
  (0, 35149)	1
  (0, 35325)	2
  (0, 35329)	4
  (0, 35364)	1
  (0, 35439)	1
  (0, 35749)	2
  (0, 35810)	8
  (0, 35824)	2
  (0, 35891)	1
  (0, 36420)	2
  (0, 36433)	1
  (0, 36638)	2
  (0, 36969)	3
  (0, 36978)	1
  (0, 37133)	2
True label: 0
Predicted label: 1
Misclassified instance:
Text:   (0, 32787)	1
True label: 1
Predicted label: 0
Misclassified instance:
Text:   (0, 6193)	1
  (0, 13150)	1
  (0, 15573)	1
  (0, 27429)	1
  (0, 29036)	1
  (0, 32787)	1
True label

In [21]:
import joblib

# Save the trained model to a file
filename = 'spam_classifier.pkl'
joblib.dump(classifier, filename)


['spam_classifier.pkl']

In [28]:
# Load the trained model from the file
loaded_model = joblib.load(filename)

# Use the model to make predictions on new data
X_new = ['URGENT! You have won a prize! Claim now!']
X_new_processed = [' '.join([stemmer.stem(word) for word in text.lower().split()]) for text in X_new]
y_pred = loaded_model.predict(vectorizer.transform(X_new_processed))

# Print the predicted class for the new data
print(y_pred)


[1]
